name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - numpy
  - pandas
  - xarray
  - zarr
  - fsspec
  - regionmask  
  - xmip
  - xgcm
  - cmocean
  - matplotlib
  - bokeh
  - intake
  - intake-esm
  - xesmf
  - cartopy
  - holoviews
  - datashader
  - dask-gateway
  - tqdm
  - nc-time-axis
  - mpltoolbox
